name: nightly

#on:
#  schedule:
#    - cron: "0 0 * * *"

on:
  push:
    branches:
      - master

jobs:

  check-updated-files:
    runs-on: self-hosted
    outputs:
      updated: ${{ steps.updatestatus.outputs.updated }}
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/hub-builder
          path: builder
          token: ${{ secrets.JINA_DEV_BOT }}
      - run: cd builder && git fetch --prune --unshallow

      - name: pull status repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/hub-status
          path: builder/status
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/api repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/api
          path: builder/api
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/jina-hub repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-hub
          path: builder/hub
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/jina repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          path: builder/src/jina
          token: ${{ secrets.JINA_DEV_BOT }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
        env:
         AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: check if there are images to build
        id: updatestatus
        run: |
          cd builder
          pip3 install -r builder/requirements.txt
          python3.7 app.py --check-targets && echo "::set-output name=updated::true" || echo "::set-output name=updated::false" || true
        env:
          MONGODB_CREDENTIALS: ${{ secrets.MONGODB_CREDENTIALS }}

  build-updated-files:
    needs: check-updated-files
    if: "needs.check-updated-files.outputs.updated == 'true'"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/hub-builder
          path: builder
          token: ${{ secrets.JINA_DEV_BOT }}
      - run: cd builder && git fetch --prune --unshallow

      - name: pull status repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/hub-status
          path: builder/status
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/api repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/api
          path: builder/api
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/jina-hub repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina-hub
          path: builder/hub
          token: ${{ secrets.JINA_DEV_BOT }}

      - name: pull jina-ai/jina repo
        uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
          path: builder/src/jina
          token: ${{ secrets.JINA_DEV_BOT }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.7
        env:
         AGENT_TOOLSDIRECTORY: /opt/hostedtoolcache

      - name: set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: build all new images
        run: |
          cd builder
          echo ${{ steps.buildx.outputs.platforms }}
          docker login -u ${{ secrets.DOCKERHUB_DEVBOT_USER }} -p ${{ secrets.DOCKERHUB_DEVBOT_TOKEN }}
          pip3 install -r builder/requirements.txt
          python3.7 app.py --bleach-first --reason "fix nightly build" --update-strategy=nightly
        env:
          MONGODB_CREDENTIALS: ${{ secrets.MONGODB_CREDENTIALS }}
          DOCKERHUB_DEVBOT_USER: ${{ secrets.DOCKERHUB_DEVBOT_USER }}
          DOCKERHUB_DEVBOT_TOKEN: ${{ secrets.DOCKERHUB_DEVBOT_TOKEN }}

      - name: commit readme and hub badge
        run: |
          cd builder/status
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          git add README.md hub-stat.svg
          git commit -qm "chore: update readme and hub badge" -a
          git show '--stat-count=10' HEAD
          git config --list

      - name: push readme and hub badge
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/hub-status
          force: true
          directory: builder/status/

      - name: commit build history
        run: |
          cd builder/api/hub
          git config --local user.email "dev-bot@jina.ai"
          git config --local user.name "Jina Dev Bot"
          git add package.json package status.json status
          git commit -qm "chore: update build history" -a
          git show '--stat-count=10' HEAD
          git config --list

      - name: push build history
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.JINA_DEV_BOT }}
          repository: jina-ai/api
          force: true
          directory: builder/api/